### PR TITLE
Merchant index #24

### LINKED ISSUE #24: User Story 46, Merchant Index Page
```
As a visitor
When I visit the merchant's index page at "/merchants"
I see all merchants in the system who are active
Next to each merchant's name I see their city and state
I also see the date they registered
```

### Checklist:

- [ ] base tests are written
- [ ] base code is written to pass tests
- [ ] edge case ("sad path") tests written (if required)
- [ ] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #25

child of #79

depends on #76

### PR DESCRIPTION
**Pull request by allieIsOkay**
Adds tests for merchant index page
Adds merchant index page
closes #24

### CODE REVIEW

**Review by timnallen — APPROVED** [review]
Nice job! We won't need a users index page except for admin viewing normal users, right? So the 'users#index' is merchants?

**Comment by csvlewis** [comment]
Good work, Peter! I just made a small change to fix a spelling error in one of the test descriptions.

**Comment by teresa-m-knowles** [comment]
> Nice job! We won't need a users index page except for admin viewing normal users, right? So the 'users#index' is merchants?

Yes, I think so.

**Review by teresa-m-knowles — APPROVED** [review]
All looks good to me. Good job on that #active_merchants method, @plapicola

**Comment by allieIsOkay** [comment]
> Good work, Peter! I just made a small change to fix a spelling error in one of the test descriptions.

Thanks Chris, good catch.

**Pull request merged**
